name: online-random
version: '0.0.1.0'
synopsis: Random numeric streams
description: Random numeric streams used to test the online library.
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day
license: BSD3
github: tonyday567/online-random
extra-source-files:
- readme.md
- stack.yaml
default-extensions:
- NoImplicitPrelude
- UnicodeSyntax
- NegativeLiterals
- OverloadedStrings
dependencies:
library:
  source-dirs: src
  exposed-modules:
  - Online.Random
  dependencies:
  - base >=4.7 && <5
  - containers
  - foldl
  - lens
  - mwc-probability
  - mwc-random
  - numhask
  - online
  - primitive
  - streaming
executables:
  orand:
    main: scratchpad.hs
    source-dirs: app
    ghc-options:
    - -funbox-strict-fields
    - -fforce-recomp
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.7 && <5
    - chart-unit
    - foldl
    - foldl
    - generic-lens-labels
    - lens
    - mwc-random
    - numhask
    - online
    - online-random
    - optparse-generic
    - protolude
    - streaming
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - base >=4.7 && <5
    - doctest
    - protolude
    - tasty
