name: online-random
version: '0.0.1'
synopsis: Random numeric streams
description: Random numeric streams used to test the online library.
category: project
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day
license: BSD3
github: tonyday567/online-random
extra-source-files:
- readme.md
- index.html
- stack.yaml
default-extensions:
- NoImplicitPrelude
- UnicodeSyntax
- BangPatterns
- BinaryLiterals
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DisambiguateRecordFields
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTSyntax
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NegativeLiterals
- OverloadedStrings
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- TupleSections
- TypeFamilies
- TypeOperators
dependencies:
- base >=4.7 && <5
- protolude
library:
  source-dirs: src
  exposed-modules:
  - Online.Random
  dependencies:
  - mwc-random
  - mwc-probability
  - numhask
  - primitive
  - streaming
executables:
  orand:
    main: scratchpad.hs
    source-dirs: app
    ghc-options:
    - -funbox-strict-fields
    - -fforce-recomp
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - numhask
    - optparse-generic
    - online-random
    - online
    - mwc-random
    - streaming
    - foldl
    - chart-unit
    - primitive
    - pretty-simple
    - containers
    - lens
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - tasty
    - doctest
