resolver: nightly-2017-11-22

packages:
  - '.'
  - ../chart-unit

extra-deps:
  - streaming-0.1.4.5
  - mmorph-1.0.9
  # - numhask-0.1.2
  # - chart-unit-0.5.1
  # - numhask-range-0.1.1
  # - online-0.2.0
