resolver: lts-14.13

packages:
  - .
  - ../online/online
  - ../chart-svg
  - ../readme-lhs

extra-deps:
  - lucid-svg-0.7.1
  - javascript-bridge-0.2.0
  - numhask-space-0.3.0
  - web-rep-0.2.0
  - box-0.1.0

allow-newer: true
